# Generated by Django 5.0.1 on 2024-01-25 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0003_alter_film_options_userfilms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="user",
        ),
        migrations.AddField(
            model_name="film",
            name="user",
            field=models.ManyToManyField(
                related_name="films",
                through="films.UserFilms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
